# ################### GLOBAL ###################

global:
  environmentName: gamma

chains:
  river:
    chainId: "6524490"
    contractAddresses:
      riverRegistry: "0xf18E98D36A6bd1aDb52F776aCc191E69B491c070"
  base:
    chainId: "84532"
    contractAddresses:
      spaceArchitect: "0x968696BC59431Ef085441641f550C8e2Eaca8BEd"
      baseRegistry: "0x08cC41b782F27d62995056a4EF2fCBAe0d3c266F"

notificationService:
  image:
    tag: "0dd86e9"
  apnsTownsAppIdentifier: com.towns.internal
  resources:
    requests:
      cpu: 1
      memory: 7Gi
    limits:
      cpu: 1
      memory: 7Gi

riverNode:
  image:
    tag: "0dd86e9"
  numStreamNodes: 11
  numArchiveNodes: 0
  riverRegistryPageSize: 1500
  race: true
  logLevel: "debug"
  resources:
    requests:
      cpu: 0.5
      memory: 1.5Gi

subgraph:
  image:
    tag: "49d065a"
  ponderStartBlock: "9378183"
  ponderLogLevel: "debug"
  nodeEnv: "development"
  secrets:
    name: "subgraph-secondary-secrets"
  resources:
    requests:
      cpu: 1.5
      memory: 2Gi
    limits:
      cpu: 2.0
      memory: 20Gi

appRegistryService:
  image:
    tag: "8781d05"
  resources:
    requests:
      cpu: 0.5
      memory: 1.5Gi
    limits:
      cpu: 1
      memory: 2Gi

rpcGateway:
  image:
    tag: "5b23033"

argocd:
  externalAccess:
    enabled: true

xchainMonitor:
  image:
    tag: "latest"
  resources:
    limits:
      cpu: 1
      memory: 5Gi
    requests:
      cpu: 0.4
      memory: 4Gi

metricsAggregator:
  prometheus:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 0.5
        memory: 1Gi
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.5
      memory: 1Gi

appOfApps:
  applications:
  - name: argocd
    namespace: argocd
    disable: false
  - name: datadog
    namespace: datadog
    disable: true
  - name: external-secrets
    namespace: external-secrets
    disable: false
  - name: cert-manager
    namespace: cert-manager
    disable: false
  - name: external-dns
    namespace: external-dns
    disable: false
  - name: main-alb
    namespace: default
    disable: false
  - name: xchain-monitor
    namespace: default
    disable: true
  - name: metrics-aggregator
    namespace: default
    disable: false
  - name: notification-service
    namespace: default
    disable: false
  - name: river-node
    namespace: default
    disable: false
  - name: subgraph
    namespace: default
    disable: false
  - name: rpc-gateway
    namespace: default
    disable: true
  - name: app-registry-service
    namespace: default
    disable: true
