# ################### GLOBAL ###################

global:
  environmentName: omega

chains:
  river:
    chainId: "550"
    contractAddresses:
      riverRegistry: "0x1298c03Fde548dc433a452573E36A713b38A0404"
  base:
    chainId: "8453"
    contractAddresses:
      spaceArchitect: "0x9978c826d93883701522d2CA645d5436e5654252"
      baseRegistry: "0x7c0422b31401C936172C897802CF0373B35B7698"

notificationService:
  image:
    tag: "750ae8a"
  resources:
    limits:
      cpu: "1.5"
      memory: "180Gi"
    requests:
      cpu: "1.5"
      memory: "80Gi"
  apnsTownsAppIdentifier: com.towns.ios # TODO: always change

riverNode:
  image:
    tag: "750ae8a"
    pullPolicy: Always
  riverRegistryPageSize: 3000
  useRpcGateway: true
  numStreamNodes: 3
  numArchiveNodes: 3
  imageTagOverride:
    archive:
      3: "589d4f8"

  apmEnabled: true
  resources:
    requests:
      cpu: 0.5
      memory: 15Gi
    limits:
      cpu: 2
      memory: 20Gi

subgraph:
  image:
    tag: "subgraph-49d065a-2"
  ponderStartBlock: "13777757"
  ponderLogLevel: "info"
  nodeEnv: "production"
  resources:
    requests:
      cpu: 2
      memory: 10Gi
    limits:
      cpu: 4
      memory: 35Gi
  secrets:
    name: "subgraph-secondary-secrets"

argocd:
  externalAccess:
    enabled: true

rpcGateway:
  image:
    tag: "5b23033"
  resources:
    requests:
      memory: "0.5Gi"
      cpu: "2.5"
    limits:
      memory: "5Gi"
      cpu: "3"

appRegistryService:
  image:
    tag: "750ae8a"
  resources:
    requests:
      cpu: 0.5
      memory: 1.5Gi
    limits:
      cpu: 1
      memory: 2Gi

xchainMonitor:
  image:
    tag: "latest"
  resources:
    limits:
      cpu: 1
      memory: 6Gi
    requests:
      cpu: 1
      memory: 5Gi

metricsAggregator:
  prometheus:
    resources:
      limits:
        cpu: 1
        memory: 20Gi
      requests:
        cpu: 1
        memory: 2Gi
  resources:
    limits:
      cpu: 1
      memory: 15Gi
    requests:
      cpu: 1
      memory: 1Gi

appOfApps:
  applications:
  - name: argocd
    namespace: argocd
    disable: false
  - name: datadog
    namespace: datadog
    disable: false
  - name: external-secrets
    namespace: external-secrets
    disable: false
  - name: cert-manager
    namespace: cert-manager
    disable: false
  - name: external-dns
    namespace: external-dns
    disable: false
  - name: main-alb
    namespace: default
    disable: false
  - name: xchain-monitor
    namespace: default
    disable: false
  - name: metrics-aggregator
    namespace: default
    disable: false
  - name: notification-service
    namespace: default
    disable: false
  - name: river-node
    namespace: default
    disable: false
  - name: subgraph
    namespace: default
    disable: false
  - name: rpc-gateway
    namespace: default
    disable: false
  - name: app-registry-service
    namespace: default
    disable: true
